---
title: "Titanic_predictions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

#install.packages('ggthemes')
#install.packages('dplyr')
#install.packages('mice')


# Load packages
library('ggplot2') # visualization
library('ggthemes') # visualization
library('scales') # visualization
library('dplyr') # data manipulation
library('mice') # imputation
library('randomForest') # classification algorithm

train <- read.csv('Titanic_train.csv', stringsAsFactors = F)
test  <- read.csv('Titanic_test.csv', stringsAsFactors = F)

full  <- bind_rows(train, test) # bind training & test data

# check data
str(full)
head(full)

# Grab title from passenger names
full$Title <- gsub('(.*, )|(\\..*)', '', full$Name)

head(full$Title)

# Show title counts by sex
#table(full$Sex, full$Title)

```












































































```{r}

# Import the dataset
training_dataset_raw=read.csv('Titanic_train.csv')
test_dataset_raw=read.csv('Titanic_test.csv')

head(training_dataset_raw)

# move the Survived column to the end of the dataframe and keep only relevant columns

#head(training_dataset_raw)
#str(training_dataset_raw)
training_dataset=data.frame(training_dataset_raw[,c(1,5,12,3,6,7,8,10,2)])
test_dataset=data.frame(test_dataset_raw[,c(1,4,11,2,5,6,7,9)])


# Encoding categorical variables and convert dependent variable to factor- training data
training_dataset$Sex=factor(training_dataset$Sex,
                       levels=c('male','female'),
                       labels=c(1,2))
training_dataset$Embarked=factor(training_dataset$Embarked,
                       levels=c('','C','Q','S'),
                       labels=c(1,2,3,4))
training_dataset$Survived=factor(training_dataset$Survived,
                       levels=c(0,1),
                       labels=c(0,1))
# Encoding categorical variables and convert dependent variable to factor- test data
test_dataset$Sex=factor(test_dataset$Sex,
                       levels=c('male','female'),
                       labels=c(1,2))
test_dataset$Embarked=factor(test_dataset$Embarked,
                       levels=c('','C','Q','S'),
                       labels=c(1,2,3,4))



# Treatment for missing Age- Training dataset
training_dataset$Age=ifelse(is.na(training_dataset$Age),
                    ave(training_dataset$Age,FUN= function(x) mean(x,na.rm=TRUE)),
                    training_dataset$Age)
# Treatment for missing Age- Test dataset
test_dataset$Age=ifelse(is.na(test_dataset$Age),
                    ave(test_dataset$Age,FUN= function(x) mean(x,na.rm=TRUE)),
                    test_dataset$Age)
# Treatment for missing Fare- Test dataset
test_dataset$Fare=ifelse(is.na(test_dataset$Fare),
                    ave(test_dataset$Fare,FUN= function(x) mean(x,na.rm=TRUE)),
                    test_dataset$Fare)


# 
# head(test_dataset)
# str(test_dataset)
# summary(test_dataset)



# Try Logistic model and look at the performance

#Feature Scaling
 # head(training_dataset)
# str(test_dataset)
# summary(test_dataset)

training_dataset[,4:8]=scale(training_dataset[,4:8])
test_dataset[,4:8]=scale(test_dataset[,4:8])

# head(test_dataset)
# str(test_dataset)
# summary(test_dataset)


# Fit logistic regression to the dataset
classifier=glm(formula=Survived~Sex+Pclass+Age+SibSp,
               family=binomial,
               data=training_dataset)
summary(classifier)

# Predict the test set result
# In the data you'll pass all the columns of test set except the dependent variable itself,so, -3
prob_pred=predict(classifier,type='response',newdata=test_dataset[,])
y_pred=ifelse(prob_pred>0.6,1,0)

results_titanic=data.frame(test_dataset$PassengerId,prob_pred)
head(results_titanic)

write.csv(results_titanic,'results_titanic.csv')
```

```{r}
# Import the dataset
training_dataset_raw=read.csv('Titanic_train.csv')
test_dataset_raw=read.csv('Titanic_test.csv')

head(training_dataset_raw)

# move the Survived column to the end of the dataframe and keep only relevant columns

#head(training_dataset_raw)
#str(training_dataset_raw)
training_dataset=data.frame(training_dataset_raw[,c(1,5,12,3,6,7,8,10,2)])
test_dataset=data.frame(test_dataset_raw[,c(1,4,11,2,5,6,7,9)])


# Encoding categorical variables and convert dependent variable to factor- training data
training_dataset$Sex=factor(training_dataset$Sex,
                       levels=c('male','female'),
                       labels=c(1,2))
training_dataset$Embarked=factor(training_dataset$Embarked,
                       levels=c('','C','Q','S'),
                       labels=c(1,2,3,4))
training_dataset$Survived=factor(training_dataset$Survived,
                       levels=c(0,1),
                       labels=c(0,1))


# Encoding categorical variables and convert dependent variable to factor- test data
test_dataset$Sex=factor(test_dataset$Sex,
                       levels=c('male','female'),
                       labels=c(1,2))
test_dataset$Embarked=factor(test_dataset$Embarked,
                       levels=c('','C','Q','S'),
                       labels=c(1,2,3,4))



# Treatment for missing Age- Training dataset
training_dataset$Age=ifelse(is.na(training_dataset$Age),
                    ave(training_dataset$Age,FUN= function(x) mean(x,na.rm=TRUE)),
                    training_dataset$Age)
# Treatment for missing Age- Test dataset
test_dataset$Age=ifelse(is.na(test_dataset$Age),
                    ave(test_dataset$Age,FUN= function(x) mean(x,na.rm=TRUE)),
                    test_dataset$Age)
# Treatment for missing Fare- Test dataset
test_dataset$Fare=ifelse(is.na(test_dataset$Fare),
                    ave(test_dataset$Fare,FUN= function(x) mean(x,na.rm=TRUE)),
                    test_dataset$Fare)


# 
# head(test_dataset)
# str(test_dataset)
# summary(test_dataset)



# Try Logistic model and look at the performance

#Feature Scaling
 # head(training_dataset)
# str(test_dataset)
# summary(test_dataset)

training_dataset[,4:8]=scale(training_dataset[,4:8])
test_dataset[,4:8]=scale(test_dataset[,4:8])

# head(test_dataset)
# str(test_dataset)
# summary(test_dataset)


# Fit model to the dataset
#install.packages('randomForest')
library(randomForest)


RF_classifier=randomForest(x=training_dataset[,2:8],y=training_dataset[,9],ntree=1000)


# Predict the test set result
y_pred=predict(RF_classifier,newdata=test_dataset[,2:8])
results_titanic=data.frame(test_dataset$PassengerId,y_pred)
head(results_titanic)

write.csv(results_titanic,'results_titanic.csv')




```



